# Site settings
name: Risa on Rails
email: risaonrails@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Risa writes about Rails, Postgres, DevOps, and other things. She loves pairing, internet memes, cats, and all the cute things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://risaonrails.com" # the base hostname & protocol for your site
permalink: /:title/
twitter_username: mookiy
github_username:  rbatta
linkedin_username: risabatta
# Build settings
markdown: kramdown
timezone: America/Los_Angeles
future: true
# boilerplate stuff
post:
  template: _post.md
  extension: md
page:
  template: _page.txt
  extension: md
editor: subl
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: git@github.com:rbatta/risa-on-rails.git